module.exports = [
    {
        first_name: 'Viktor',
        last_name: 'Walker',
        email: 'viktor@gmail.com',
        phone: '1 111 111 111',
        bank_id: '11',
        branch_code: '95',
        password: '$2a$10$xSXNLc9I/D8/xWwBLuj/guBV1r8ORl9g1Owm7ZiWKXO0sp7nkh2CO', //Vvvvvvv1
        account_number: 123456789,
        resetPasswordToken: '',
        resetPasswordExpires: null,
        email_conf: false ,
        phone_conf: false,
        project_running_notification: true,
        project_subscription_notification: false,
        project_purchases_notification: true,
        project_deleted_notification: false,
        project_edited_notification: false,
        project_days_left_notification: false,
    },
    {
        first_name: 'Mario',
        last_name: 'Super',
        email: 'mario@gmail.com',
        phone: '1 222 333 444',
        bank_id: '13',
        branch_code: '143',
        password: '$2a$10$0ZTlpVU0a0bHODCzvCDvqe.xo5crQHENvq2LjIXu21RNJjtoKKbgi', // Mmmmmmm1
        account_number: 123456789,
        resetPasswordToken: '',
        resetPasswordExpires: null,
        email_conf: false ,
        phone_conf: false,
        project_running_notification: true,
        project_subscription_notification: false,
        project_purchases_notification: true,
        project_deleted_notification: false,
        project_edited_notification: false,
        project_days_left_notification: false,
    },
    {
        first_name: 'Bruce',
        last_name: 'Wyne',
        email: 'bruce@gmail.com',
        phone: '1 777 888 999',
        bank_id: '22',
        branch_code: '1',
        password: '$2a$10$O4nBrILq9kIJiC0CfVAgn.zppOEXSzOuQFZHz9fjjZAze7kG8XB96', //Bbbbbbb1
        account_number: 123456789,
        resetPasswordToken: '',
        resetPasswordExpires: null,
        email_conf: false ,
        phone_conf: false,
        project_running_notification: true,
        project_subscription_notification: false,
        project_purchases_notification: true,
        project_deleted_notification: false,
        project_edited_notification: false,
        project_days_left_notification: false,
    },
    {
        first_name: 'Captain',
        last_name: 'America',
        email: 'captain@gmail.com',
        phone: '1 777 222 666',
        bank_id: '39',
        branch_code: '1',
        password: '$2a$10$soYFaR6uQ..Cci/LF22PquNbweHAZULee7lrC4viGo0XRrkKsukn6', //Ccccccc1
        account_number: 123456789,
        resetPasswordToken: '',
        resetPasswordExpires: null,
        email_conf: false ,
        phone_conf: false,
        project_running_notification: true,
        project_subscription_notification: false,
        project_purchases_notification: true,
        project_deleted_notification: false,
        project_edited_notification: false,
        project_days_left_notification: false,
    }
]




